//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.09 at 11:26:20 AM CEST 
//


package org.n52.restfulwpsproxy.webapp.soap.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.n52.restfulwpsproxy.webapp.soap.message.WPSResponse;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="wpsResponse" type="{http://org/n52/restfulwpsproxy/webapp/soap/message}WPSResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "wpsResponse"
})
@XmlRootElement(name = "WPSOperationResponse")
public class WPSOperationResponse {

    @XmlElement(required = true)
    protected WPSResponse wpsResponse;

    /**
     * Gets the value of the wpsResponse property.
     * 
     * @return
     *     possible object is
     *     {@link WPSResponse }
     *     
     */
    public WPSResponse getWpsResponse() {
        return wpsResponse;
    }

    /**
     * Sets the value of the wpsResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link WPSResponse }
     *     
     */
    public void setWpsResponse(WPSResponse value) {
        this.wpsResponse = value;
    }

}
