//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.09 at 11:26:20 AM CEST 
//


package org.n52.restfulwpsproxy.webapp.soap.message;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.n52.restfulwpsproxy.webapp.soap.message package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _WPSResponse_QNAME = new QName("http://org/n52/restfulwpsproxy/webapp/soap/message", "WPSResponse");
    private final static QName _WPSRequest_QNAME = new QName("http://org/n52/restfulwpsproxy/webapp/soap/message", "WPSRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.n52.restfulwpsproxy.webapp.soap.message
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link WPSRequest }
     * 
     */
    public WPSRequest createWPSRequest() {
        return new WPSRequest();
    }

    /**
     * Create an instance of {@link WPSResponse }
     * 
     */
    public WPSResponse createWPSResponse() {
        return new WPSResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WPSResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org/n52/restfulwpsproxy/webapp/soap/message", name = "WPSResponse")
    public JAXBElement<WPSResponse> createWPSResponse(WPSResponse value) {
        return new JAXBElement<WPSResponse>(_WPSResponse_QNAME, WPSResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WPSRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://org/n52/restfulwpsproxy/webapp/soap/message", name = "WPSRequest")
    public JAXBElement<WPSRequest> createWPSRequest(WPSRequest value) {
        return new JAXBElement<WPSRequest>(_WPSRequest_QNAME, WPSRequest.class, null, value);
    }

}
